FROM php:8.1-zts

RUN apt-get update && apt-get install -y \
        git \
        zip \
        curl \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update \
    && apt-get install -y libpq-dev

RUN docker-php-ext-configure pcntl --enable-pcntl \
  && docker-php-ext-install \
    pcntl

COPY --from=composer /usr/bin/composer /usr/bin/composer
