version: '3'

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: DockerFile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    user: 1000:1000
    command: php -S 0.0.0.0:8000 -t /app
    working_dir: /app